### ISSUE TITLE
Fix tweet text.

### ISSUE THREAD

**Issue by shreybatra** [shreybatra/Twitter-Stream-API-Dataset#17]
Currently only a jist of the whole text is coming. Fix it by actually using the full text of tweet.

**Comment by MinoLiu** [comment]
Hello, can I add pipenv to your project?
Also this bug ill fix it

**Comment by shreybatra** [comment]
Upload a PR please.

**Comment by MinoLiu** [comment]
@shreybatra Uploaded, please review
