### ISSUE TITLE
API 2 : Browser display limit issue 

### ISSUE THREAD

**Issue by jatin69** [shreybatra/Twitter-Stream-API-Dataset#4]
MongoDB database has 300+ tweets on that topic. But, get tweets api in browser with even 100 limit, hardly has 10 results. Don't know why

**Comment by shreybatra** [comment]
This database works with "stream API". It means it triggers the search, then waits for a "new" tweet to be posted on that filter which you apply. STREAM API works on tweets tweeted AFTER you start the trigger. You might want to you SEARCH API to get past tweets.

Please wait for 300+ tweets to be tweeted on the topic which you are filtering. You can check the number of tweets posted by applying /gettweets with limit 300 and see how many already have been posted.

Regards

**Comment by jatin69** [comment]
My point is, I want only 100 tweets. so I set the limit to 100.
but in MongoDB, it keeps on going 100..200...300
Also, API 2 isn't able to display those 100/200/300 in the browser.  Any ideas?

**Comment by jatin69** [comment]
My bad. I was using `max_tweets` instead of `limit`.
Works well now. thanks.
