### ISSUE TITLE
Enhancement in database schema

### ISSUE THREAD

**Issue by jatin69** [shreybatra/Twitter-Stream-API-Dataset#5]
Currently, it creates a `tweets` table and stores there.
But if I switch to a new topic, it keeps on appending data in `tweets`.
Maybe we should make a separate table for each search query.
So I can actively have data on multiple topics.

**Comment by shreybatra** [comment]
It does not make a new table. This is NoSQL database, it creates a collection. No point to create a different collection everytime. You can go through my this for help.

[This Blog](https://www.eazydevelop.com/2018/03/mongodb-and-integration-with-flask.html)

Also read, documentation of MongoDB and how it is different from Classic SQL in tables and records sort of way.!

Cheers!
